# Generated by Django 4.2.7 on 2023-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0002_usuario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Senha'),
        ),
    ]
