# Generated by Django 4.2.7 on 2023-12-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0003_remove_usuario_senha_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
