# Generated by Django 4.2.7 on 2023-12-01 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0004_chamado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
