# Generated by Django 4.2.7 on 2023-12-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0006_chamado_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='responsavel',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Aluno', 'Aluno')], default='1', max_length=8, verbose_name='Tipo de Usuário'),
        ),
    ]
