# Generated by Django 4.2.7 on 2023-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0007_remove_chamado_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='siape',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Siape'),
        ),
    ]
