# Generated by Django 4.2.7 on 2023-12-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0008_usuario_siape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='siape',
            field=models.CharField(default='', max_length=50, verbose_name='Siape'),
        ),
    ]
