# Generated by Django 4.2.7 on 2023-12-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0009_alter_usuario_siape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='siape',
        ),
    ]
