# Generated by Django 4.2.7 on 2023-12-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0010_remove_usuario_siape'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='siape',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SIAPE'),
        ),
    ]
