# Generated by Django 4.2.7 on 2023-12-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0011_usuario_siape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='id',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
