# Generated by Django 4.2.7 on 2023-12-09 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysapp', '0013_chamado_estado_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
